# -*- coding: utf-8 -*-
"""CivicFlow_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jcibK6RhKJtuXOo8YpzDXlBSRXBzlDSK
"""

!pip install replicate

import os
import uuid
import replicate
from getpass import getpass

# --- 1. SETUP & AUTHENTICATION ---


os.environ["REPLICATE_API_TOKEN"] = " REPLACE WITH UR API TOKEN "

# Using the efficient IBM Granite 4.0 model
MODEL_ID = "ibm-granite/granite-4.0-h-small"

# --- 2. BACKEND SYSTEMS (Simulated) ---

class SMSGateway:
    """Simulates sending SMS updates."""
    @staticmethod
    def send_sms(recipient, message):
        print(f"   [SMS] 📨 To {recipient}: \"{message}\"")

class TicketingAPI:
    """Simulates creating official government tickets."""
    @staticmethod
    def generate_ticket(complaint_details):
        # Generate a unique ticket ID (e.g., TKT-2026-X892)
        ticket_id = f"TKT-2026-{str(uuid.uuid4())[:4].upper()}"
        print(f"   [TICKET] 🎫 Official Ticket Created: {ticket_id}")
        return ticket_id

class RAGSystem:
    """Simulates searching the government database for answers."""
    @staticmethod
    def retrieve_answer(query):
        print(f"   [DATABASE] 🔍 Searching rules and regulations...")
        # We ask Granite to act as the knowledge base here
        prompt = f"""
        You are a helpful government information assistant.
        User Question: {query}
        Provide a concise, polite answer explaining the procedure or rules.
        """
        output = replicate.run(
            MODEL_ID,
            input={"prompt": prompt, "max_new_tokens": 200, "temperature": 0.3}
        )
        return "".join(output)

# --- 3. MAIN AI BRAIN (CivicFlow) ---

class CivicFlowAgent:
    def __init__(self):
        self.rag = RAGSystem()
        self.ticketing = TicketingAPI()
        self.sms = SMSGateway()

    def classify_intent(self, user_text):
        """Decides if the input is a 'QUERY' (Doubt) or 'GRIEVANCE' (Complaint)."""
        prompt = f"""
        Classify this text into exactly one category: 'QUERY' or 'GRIEVANCE'.
        - QUERY: Asking for info, rules, or how-to.
        - GRIEVANCE: Reporting a broken thing, delay, or bad service.

        Text: "{user_text}"

        Reply ONLY with the word QUERY or GRIEVANCE.
        """
        output = replicate.run(
            MODEL_ID,
            input={"prompt": prompt, "max_new_tokens": 10}
        )
        classification = "".join(output).strip().upper()
        if "GRIEVANCE" in classification: return "GRIEVANCE"
        return "QUERY"

    def process_input(self, user_text):
        print(f"\n⚙️ Analyzing...")

        # 1. Classify
        intent = self.classify_intent(user_text)
        print(f"   [AI LOGIC] Detected Intent: {intent}")

        # 2. Route based on intent
        if intent == "QUERY":
            # Path A: Answer the doubt
            answer = self.rag.retrieve_answer(user_text)
            print(f"\n✅ CIVICFLOW RESPONSE:\n{answer}")

        elif intent == "GRIEVANCE":
            # Path B: Create Ticket & Notify
            ticket_id = self.ticketing.generate_ticket(user_text)

            # Notify Official
            self.sms.send_sms("OFFICIAL_OFFICER", f"New Complaint: {user_text}")

            # Notify Citizen
            print(f"\n✅ CIVICFLOW RESPONSE:\nYour complaint has been registered. Ticket ID: {ticket_id}. An officer has been notified.")

# --- 4. INTERACTIVE LOOP ---

def start_app():
    agent = CivicFlowAgent()

    print("\n" + "="*40)
    print("      🏛️  CIVICFLOW AI STARTED  🏛️")
    print("="*40)
    print("Type 'exit' to quit.\n")

    while True:
        try:
            # Ask User for Input
            user_input = input("\n🗣️  Enter your query or complaint: ")

            if user_input.lower() in ['exit', 'quit']:
                print("Shutting down...")
                break

            if not user_input.strip():
                continue

            # Process it
            agent.process_input(user_input)

        except Exception as e:
            print(f"\n❌ Error: {e}")

# Run the app
if __name__ == "__main__":
    start_app()